- name: Run
  env:
    FEISHU_APP_ID:     ${{ secrets.FEISHU_APP_ID }}
    FEISHU_APP_SECRET: ${{ secrets.FEISHU_APP_SECRET }}
    FEISHU_APP_TOKEN:  ${{ secrets.FEISHU_APP_TOKEN }}
    FEISHU_TABLE_ID:   ${{ secrets.FEISHU_TABLE_ID }}
  run: |
    python scripts/issue_to_feishu_ids.py
